title: software Works
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 I am a Full Stack Software Developer with extensive experience in building highly scalable web applications. 
 I specialize in C# and have professional experience working with JavaScript and React. 
 I enjoy learning new technologies and writing code. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
